site_name: Estudos Certificação OCI
repo_url: https://github.com/luanmds/oracle_certifications_study
repo_name: luanmds/oracle_certifications_study
pages: 
  - Home: 'index.md'
  - Arquitetura OCI: 'oci_architecture.md'
  - IAM: 'IAM.md'
  - Networking: 'networking.md'
  - Compute: 'compute.md'
  - Storage: 'storage.md'
  - Databases: 'database.md'
  - Security: 'security.md'
  - AppDev: 'app_dev.md'
  - Observability and Monitoring: 'observ_management.md'
theme:
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: grey
    accent: deep orange
    scheme: slate
  